cdvp/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include(('visualize.urls', 'visualize'), namespace='visualize')),
]

visualize/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('features', views.features, name='features'),
    path('application', views.application, name='application'),
    path('about', views.about, name='about'),

    path('api/example', views.example, name='example'),
    path('api/generate/newman_watts_strogatz',
         views.generate_newman_watts_strogatz,
         name='generate_newman_watts_strogatz'),
    path('api/visualize', views.visualize, name='visualize'),
]

visualize/forms.py
from django import forms


TYPE_CHOICES = (
    ('input', 'Input'),
    ('file', 'File'),
    ('example', 'Example'),
    ('generate', 'Generate'),
    )

EXAMPLE_CHOICES = (
    ('karate_club', "Zachary's karate club"),
    ('davis_southern_women', "Davis' Southern women social network"),
    ('florentine_families', 'Florentine families network'),
    ('les_miserables', 'Characters in the novel Les Miserables'),
    )

GRAPH_CHOICES = (
    ('graph', 'Undirected Graph'),
    ('digraph', 'Directed Graph'),
    )
METHOD_CHOICES = (
    # networkx
    ('greedy_modularity_maximization', 'Greedy Modularity Maximization'),
    ('louvain_community_detection', 'Louvain Community Detection'),
    ('label_propagation', 'Label Propagation'),
    ('asynchronous_label_propagation', 'Asynchronous Label Propagation'),
    # karateclub
    ('karateclub_GEMSEC', 'GEMSEC'),
    ('karateclub_EdMot', 'EdMot'),
    ('karateclub_SCD', 'SCD'),
    # custom
    ('custom', 'Custom'),
    )
LAYOUT_CHOICES = (
    ('spring', 'spring'),
    ('circular', 'circular'),
    ('kamada_kawai', 'Kamada-Kawai'),
    ('shell', 'shell'),
    ('planar', 'planar'),
    ('spiral', 'spiral'),
    )

METHOD_UNWEIGHTED = (
    'label_propagation'
    )

class GraphVizForm(forms.Form):
    input_type = forms.ChoiceField(label='Input Type:', choices=TYPE_CHOICES)

    # input
    graph_input_text = forms.CharField(
        label='Graph Data:', widget=forms.Textarea, required=False)
    # file
    graph_input_file = forms.FileField(
        label='Graph File:', widget=forms.ClearableFileInput, required=False)
    # input & file
    graph_type = forms.ChoiceField(
        label='Graph Type:', choices=GRAPH_CHOICES, required=False)
    graph_weighted = forms.BooleanField(label='is weighted', required=False)
    # example
    graph_input_example = forms.ChoiceField(
        label='Example Name:', choices=EXAMPLE_CHOICES, required=False)
    # generate
    generate_arg_n = forms.IntegerField(label='n', required=False)
    generate_arg_k = forms.IntegerField(label='k', required=False)
    generate_arg_p = forms.FloatField(label='p', required=False)
    generate_arg_seed = forms.IntegerField(label='seed', required=False)

    methods = forms.MultipleChoiceField(
        label='Methods Selected:', choices=METHOD_CHOICES,
        widget=forms.CheckboxSelectMultiple)
    layout = forms.ChoiceField(
        label='Layout Selected:', choices=LAYOUT_CHOICES)
    custom_code = forms.FileField(
        label='', widget=forms.ClearableFileInput(attrs={'multiple': True}),
        required=False,
        help_text='related files when <i>Custom</i> is selected, and main.* is needed.')

    def clean(self):
        cleaned_data = super().clean()

        # TODO: form check
        # print('cleaned_data: ', cleaned_data)
        #
        # is_weighted = cleaned_data['graph_weighted']
        # method_list = cleaned_data['methods']
        #
        # if is_weighted:
        #     if len(cleaned_data['graph_input'].split()) % 3 != 0:
        #         raise forms.ValidationError('Invalid graph data.')
        #     invalid_methods = []
        #     for method in method_list:
        #         if method in METHOD_UNWEIGHTED:
        #             invalid_methods.append(method)
        #     if len(invalid_methods) > 0:
        #         message = ''
        #         for method in invalid_methods:
        #             message += "'" + method.replace('_', ' ').title() + "'"
        #         message += 'can only be used in an unweighted graph.'
        #         raise forms.ValidationError(message)
        # else:
        #     if len(cleaned_data['graph_input'].split()) % 2 != 0:
        #         raise forms.ValidationError('Invalid graph data.')
        return cleaned_data

visualize/views.py
import json, os, re

from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.http import JsonResponse
from django.shortcuts import render
import karateclub.community_detection.non_overlapping as kc_com_n
import networkx as nx
import networkx.algorithms.community as nx_com

from .forms import GraphVizForm
from .visualize import graph_viz, size_distribution
from .docker_engine.docker_eni import get_output
from datetime import datetime


def easy_asyn_lpa_communities(G, weight=None, seed=None):
    community_set = []
    community_gen = nx_com.asyn_lpa_communities(G, weight, seed)
    for community in community_gen:
        community_set.append(community)
    return community_set

# 根据 algorithm_name 得到对应算法
def choose_algo(graph, is_weighted, algorithm_name):
    ALGORITHMS = {
        'greedy_modularity_maximization': nx_com.greedy_modularity_communities,
        'louvain_community_detection': nx_com.louvain.louvain_communities,
        'label_propagation': nx_com.label_propagation_communities,
        'asynchronous_label_propagation': easy_asyn_lpa_communities,
    }
    if algorithm_name not in ALGORITHMS:
        raise RuntimeError('no method named ' + algorithm_name)
    algo = ALGORITHMS[algorithm_name]
    if is_weighted:
        return algo(graph, weight='weight')
    return algo(graph)


def choose_karateclub_algo(graph, model_name):
    MODELS = {
        'GEMSEC': kc_com_n.GEMSEC(),
        'EdMot': kc_com_n.EdMot(),
        'SCD': kc_com_n.SCD(),
    }
    if model_name not in MODELS:
        raise RuntimeError('no model named ' + model_name)
    model = MODELS[model_name]
    model.fit(graph)
    memberships = model.get_memberships()
    community_set = {}
    for x, com in memberships.items():
        try:
            community_set[com].append(x)
        except:
            community_set[com] = [x]
    return [frozenset(l) for l in community_set.values()]


# 根据 layout_name 得到对应布局方式
def choose_layout(layout_name):
    LAYOUTS = {
        'spring': nx.spring_layout,
        'circular': nx.circular_layout,
        'kamada_kawai': nx.kamada_kawai_layout,
        'shell': nx.shell_layout,
        'planar': nx.planar_layout,
        'spiral': nx.spiral_layout,
    }
    if layout_name not in LAYOUTS:
        raise RuntimeError('no layout named ' + layout_name)
    return LAYOUTS[layout_name]

# 根据 graph_type 得到图的类型
def choose_graph(graph_type):
    TYPES = {
        'graph': nx.Graph(),
        'digraph': nx.DiGraph(),
    }
    if graph_type not in TYPES:
        raise RuntimeError('no graph type named ' + graph_type)
    return TYPES[graph_type]

# 根据 layout 和 methods 的设置对 graph 施以可视化
def process_methods(graph, layout, methods, is_weighted, filepath = ''):
    graph = nx.convert_node_labels_to_integers(graph)

    layout_algo = choose_layout(layout)
    results = []
    for method in methods:
        current = {}

        if method == 'custom':
            community_set = get_output(filepath)
            current['method'] = 'Custom'
        elif 'karateclub' in method:
            formed_method = method.split('_', 1)[-1]
            community_set = choose_karateclub_algo(
                graph.copy(), formed_method)
            current['method'] = formed_method.replace('_', ' ')
        else:
            community_set = choose_algo(graph, is_weighted, method)
            current['method'] = method.replace('_', ' ').title()

        current['modularity'] = nx_com.quality.modularity(graph, community_set)
        current['coverage'], current['performance'] = \
            nx_com.quality.partition_quality(graph, community_set)
        current['graph_viz'] = graph_viz(
            graph, community_set, layout_algo).getvalue()
        current['size_distribution'] = size_distribution(
            community_set).getvalue()

        results.append(current)
    return results


def visualize(request):
    if request.method == 'POST':
        filepath = ''
        data = request.POST

        config = json.loads(data['config'])
        methods, layout = config['methods'], config['layout']

        graph_data = json.loads(data['graph_data'])

        input_type = data['type']
        if input_type == 'input':
            is_weighted = graph_data['weighted']
            graph = choose_graph(graph_data['graph_type'])

            edge_list = graph_data['edge_list']
            if is_weighted:
                graph.add_weighted_edges_from(edge_list)
            else:
                graph.add_edges_from(edge_list)
        elif input_type == 'file':
            is_weighted = graph_data['weighted']
            graph = choose_graph(graph_data['graph_type'])

            edge_list = request.FILES.get('edge_list').read().split()
            ne = len(edge_list)
            if is_weighted:
                for i in range(0, ne, 3):
                    u, v, w = [int(val) for val in edge_list[i:i+3]]
                    graph.add_edge(u, v, weight=w)
            else:
                for i in range(0, ne, 2):
                    u, v = [int(val) for val in edge_list[i:i+2]]
                    graph.add_edge(u, v)
        elif input_type == 'example':
            is_weighted = False
            graph = get_example(graph_data['name'])
        elif input_type == 'generate':
            n, k, p = graph_data['n'], graph_data['k'], graph_data['p']
            seed = None
            if 'seed' in graph_data:
                seed = graph_data['seed']
            is_weighted = False
            graph = nx.generators.random_graphs.newman_watts_strogatz_graph(
                n, k, p, seed)
        else:
            return JsonResponse()

        if 'custom' in methods:
            file_list = request.FILES.getlist('code')
            now = str(datetime.now()).replace(' ', '_').replace('.', '_').replace(':', '_')
            path = (os.path.abspath('.') + '/' + now).replace('\\', '/')
            for file in file_list:
                default_storage.save(path + '/' + file.name, file)

            pattern = re.compile(r"^main\.\w+$")

            main_files = []
            for file in file_list:
                if pattern.match(file.name):
                    main_files.append(file.name)

            if len(main_files) > 1:
                raise Exception("Multiple 'main' files found: {}".format(main_files))

            if len(main_files) == 0:
                raise Exception("No 'main' file found.")
            filepath = path + '/' +main_files[0]

            graph_content = ''
            if is_weighted:
                weights = nx.get_edge_attributes(graph, 'weight')
                for edge in graph.edges:
                    graph_content += str(edge[0]) + ' ' + str(edge[1]) + str(weights[edge]) + '\n'
            else:
                for edge in graph.edges:
                    graph_content += str(edge[0]) + ' ' + str(edge[1]) + '\n'
            default_storage.save(path + '/' + 'dataset', ContentFile(graph_content))

        content = {
            'results': process_methods(graph, layout, methods, is_weighted, filepath),
            }
        return JsonResponse(content)


def get_example(network_name):
    EXAMPLES = {
        'karate_club': nx.karate_club_graph(),
        'davis_southern_women': nx.davis_southern_women_graph(),
        'florentine_families': nx.florentine_families_graph(),
        'les_miserables': nx.les_miserables_graph(),
    }
    if network_name not in EXAMPLES:
        raise RuntimeError('no example named ' + network_name)
    graph = EXAMPLES[network_name]
    return nx.convert_node_labels_to_integers(graph)

# 根据请求选择样例
def example(request):
    if request.method == 'GET':
        graph_json = {
            'graph_type': 'graph',
            'weighted': False,
            'edge_list': list(get_example(request.GET['q']).edges),
        }
        return JsonResponse(graph_json)


# 根据输入生成对应 Newman–Watts–Strogatz small-world 图
def generate_newman_watts_strogatz(request):
    if request.method == 'GET':
        n, k = int(request.GET['n']), int(request.GET['k'])
        p = float(request.GET['p'])
        seed = None
        if 'seed' in request.GET:
            seed = int(request.GET['seed'])
        content = {
            "graph_data": "graph",
            "weighted": False,
            "edge_list":
                list(nx.generators.random_graphs.newman_watts_strogatz_graph(
                    n, k, p, seed).edges),
        }
        return JsonResponse(content)


def index(request):
    return render(request, 'visualize/index.html')

def features(request):
    return render(request, 'visualize/features.html')

def application(request):
    results = {}

    if request.method != 'POST':
        form = GraphVizForm()
    else:
        form = GraphVizForm(request.POST, request.FILES)
        if form.is_valid():
            filepath = ''
            data = form.cleaned_data
            methods, layout = data['methods'], data['layout']

            input_type = data['input_type']
            if input_type == 'input':
                is_weighted = data['graph_weighted']
                graph = choose_graph(data['graph_type'])
                edge_list = data['graph_input_text'].split()

                ne = len(edge_list)
                if is_weighted:
                    for i in range(0, ne, 3):
                        u, v, w = [int(val) for val in edge_list[i:i+3]]
                        graph.add_edge(u, v, weight=w)
                else:
                    for i in range(0, ne, 2):
                        u, v = [int(val) for val in edge_list[i:i+2]]
                        graph.add_edge(u, v)
            elif input_type == 'file':
                is_weighted = data['graph_weighted']
                graph = choose_graph(data['graph_type'])

                # TODO: file
                edge_list = request.FILES['graph_input_file'].read().split()
                ne = len(edge_list)
                if is_weighted:

visualize/templates/visualize/about.html
{% extends "visualize/base.html" %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}

  <div class="container py-2">
    <footer class="pb-2 mb-3">

      <div class="d-flex flex-column flex-sm-row justify-content-between py-4 my-4 border-top">
        <p>&copy; 2022-2023 <a href="https://github.com/Byebye-procrastinating">Byebye-procrastinating</a>.</p>
      </div>
    </footer>
  </div>

{% endblock content %}

visualize/templates/visualize/application.html
{% extends "visualize/base.html" %}

{% load django_bootstrap5 %}
{% load static %}

{% block content %}
  <div class="container">
    <form name="graph_input" action="{% url 'visualize:application' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row row-cols-2">
        <div class="col">
          <ul class="nav nav-tabs mb-2" id="tablist" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link active" id="input-tab" data-bs-toggle="tab" data-bs-target="#input" type="button" role="tab" aria-controls="input" aria-selected="true">
                Input
              </button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link" id="file-tab" data-bs-toggle="tab" data-bs-target="#file" type="button" role="tab" aria-controls="file" aria-selected="false">
                File
              </button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link" id="example-tab" data-bs-toggle="tab" data-bs-target="#example" type="button" role="tab" aria-controls="example" aria-selected="false">
                Example
              </button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link" id="generate-tab" data-bs-toggle="tab" data-bs-target="#generate" type="button" role="tab" aria-controls="generate" aria-selected="false">
                Generate
              </button>
            </li>
            <script>
              var triggerTabList = document.querySelectorAll('button[data-bs-toggle="tab"]')
              triggerTabList.forEach(tabEl => {
                tabEl.addEventListener('show.bs.tab', function (event) {
                  const activeTabId = event.target.getAttribute('aria-controls')
                  document.forms['graph_input']['input_type'].value = activeTabId
                })
              })
            </script>
          </ul>

          <div class="tab-content" id="tabContent">
            <div class="tab-pane fade show active" id="input" role="tabpanel" aria-labelledby="input-tab">
              {% bootstrap_field form_graph_input.graph_input_text %}
              {% bootstrap_field form_graph_input.graph_type %}
              {% bootstrap_field form_graph_input.graph_weighted %}
            </div>
            <div class="tab-pane fade" id="file" role="tabpanel" aria-labelledby="file-tab">
              {% bootstrap_field form_graph_input.graph_input_file %}
              {% bootstrap_field form_graph_input.graph_type %}
              {% bootstrap_field form_graph_input.graph_weighted %}
            </div>
            <div class="tab-pane fade" id="example" role="tabpanel" aria-labelledby="example-tab">
              {% bootstrap_field form_graph_input.graph_input_example %}
            </div>
            <div class="tab-pane fade" id="generate" role="tabpanel" aria-labelledby="generate-tab">
              {% bootstrap_field form_graph_input.generate_arg_n layout="horizontal" %}
              {% bootstrap_field form_graph_input.generate_arg_k layout="horizontal" %}
              {% bootstrap_field form_graph_input.generate_arg_p layout="horizontal" %}
              {% bootstrap_field form_graph_input.generate_arg_seed layout="horizontal" %}
            </div>
          </div>
        </div>
        <div class="col">
          {% bootstrap_field form_graph_input.input_type %}
          {% bootstrap_field form_graph_input.methods %}
          {% bootstrap_field form_graph_input.custom_code %}
          {% bootstrap_field form_graph_input.layout %}
          {% bootstrap_button "Draw" button_class="btn-primary btn-sm" %}
        </div>
      </div>
    </form>
    {% for result in results %}
      <h3>
        {{ result.method }}
      </h3>
      <div class="row">
        <div class="col-xs">
          Modularity: {{ result.modularity|floatformat:5 }}
          <br>
          Coverage: {{ result.coverage|floatformat:5 }} Performance: {{ result.performance|floatformat:5 }}
        </div>
        <div class="col">
          {% autoescape off %}
            {{ result.graph_viz }}
          {% endautoescape %}
        </div>
        <div class="col">
          {% autoescape off %}
            {{ result.size_distribution }}
          {% endautoescape %}
        </div>
      </div>
    {% endfor %}
  </div>

  <!--
  <div style="text-align: left;" class="btn-group" role="group">
    {% bootstrap_button "Download as PNG" button_type="button" button_class="btn-secondary btn-sm" %}
    {% bootstrap_button "Download as PDF" button_type="button" button_class="btn-secondary btn-sm" %}
    {% bootstrap_button "Download as SVG" button_type="button" button_class="btn-secondary btn-sm" %}
  </div>
  -->

{% endblock content %}

visualize/templates/visualize/base.html
{% load django_bootstrap5 %}

<!DOCTYPE html>
<html lang="zh">
  <head>
    <meta charset="utf-8">
    <meta name="viewpoint" content="width=device-width, initial-scale=1">

    <title>Community Detection Visualization Platform</title>
    <link rel="icon" type="image/x-icon" href="static/favicon.svg" />

    {% bootstrap_css %}
    {% bootstrap_javascript %}
  </head>
  <body>

    <div class="container py-2">
      <header class="pb-2 mb-3 border-bottom">
        <nav class="navbar navbar-expand-lg navbar-light">
          <div class="container">

            <a class="navbar-brand" href="{% url 'visualize:index' %}">
              Community Detection Visualization Platform
            </a>

            <div class="navbar-expand">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'visualize:index' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'visualize:features' %}">Features</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'visualize:application' %}">Application</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" aria-current="page" href="{% url 'visualize:about' %}">About</a>
                </li>
              </ul>
            </div>

          </div>
        </nav>
      </header>
    </div>

    <div class="container">
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div>

  </body>
</html>

visualize/templates/visualize/index.html
{% extends "visualize/base.html" %}

{% load django_bootstrap5 %}
{% load static %}

{% block content %}

<div class="container my-3">
  <div class="row p-4 pb-0 pe-lg-0 pt-lg-5 align-items-center rounded-3 border shadow-lg">
    <div class="col-lg-7 p-3 p-lg-5 pt-lg-3">
      <h1 class="display-6 fw-bold lh-1 mb-3">Community Detection Visualization Platform</h1>
      <p class="lead">An easy access community detectioin visualization platform.</p>
      <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
        <a href="{% url 'visualize:application' %}">
        <button type="button" class="btn btn-primary btn-lg px-4 me-md-2 fw-bold">
          Try it now
        </button>
        </a>
        <a href="{% url 'visualize:features' %}">
          <button type="button" class="btn btn-outline-secondary btn-lg px-4">
            Learn more
          </button>
        </a>
      </div>
    </div>
    <div class="col-lg-4 offset-lg-1 p-0 overflow-hidden shadow-lg">
        <img class="img-fluid rounded-lg-3" src="static/img/example-2.png" alt="" width="720">
    </div>
  </div>

  <footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item">
        <a href="{% url 'visualize:index' %}" class="nav-link px-2 text-muted">Home</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'visualize:features' %}" class="nav-link px-2 text-muted">Features</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'visualize:application' %}" class="nav-link px-2 text-muted">Application</a>
      </li>
      <li class="nav-item">
        <a href="{% url 'visualize:about' %}" class="nav-link px-2 text-muted">About</a>
      </li>
    </ul>
    <p class="text-center text-muted">
      &copy; 2022-2023 <a href="https://github.com/Byebye-procrastinating">Byebye-procrastinating</a>.
    </p>
  </footer>
</div>

{% endblock content %}